classdef spectra_Class < handle
    %Spectra Class contains all of the common GUI functionality for the
    %Spectra GUIS.
    %   It controls the basic interfaces and common handles for things like
    %   controlling the x limits and sizing the various components.
    
    %Author: Mirae Parker
    %Last Edit: 19.08.16

    
    properties
                                 %GUI Objects
        body                    %the container/background for the whole app
        background              %the axis for the background image
        graph                   %the axis for the graph
        xMin                    %the editable text which changes the XMin_Num
        xMax                    %the editable text which changes the XMax_Num
        scans                   %the editable text which changes the Scans_Num
        integration             %%the editable text which changes the Int_Num
        xMin_Label              %Holds text label for XMin Button
        xMax_Label              %Holds text label for XMax Button
        scans_Label             %Holds text label for Scans Button
        int_Label               %Holds text label for Int Button
        limits_Panel            %The panel containing the X Limit controls
        specta_Panel            %The panel containing the scans/int controls
        sample_Panel            %The panel for the dark (and in subclasses) light sampling
        dark_Sample             %The toggle-button for the Dark background sample 
        pause                   %UIControl to pause graphing
        close                   %UIcontrol to stop graphing and exit program
        custom_Text             %UI text box for custom Sample names.
        delete
        spectIndex              %Listbox to select which spectrometer to use
        
                        %Variables for Data Processing
        dark_Spectrum ;         %stores the electrical dark vector sample       
        dark_Size = 0;          %records how many spectra have been used to make the daks sample
        new_Dark = 1;           %tracks if it is the first dark-spectra
        dark_Bool = 0;          %records whether or not the program should be collecting dark samples
        scans_Num = 2;          %the number of scans to average the spectrometer should take
        int_Num = 100;          %the integration time of the spectrometer in ms
        xMin_Num                %the min x axis value displayed.
        xMax_Num                %the max x axis value displayed
        spectrum                %stores the latest spectrum from spectrometer
        wavelengths             %stores the latest wavelengths from the spectrometer
        picture                 %holds the image that is put on the background
        keepGraphing = 1;       %keeps track of whether subclasses should keep updating. 
        halt = 0;               %Boolean for tracking if the graphing should be paused
        saved_Spectra           %The container for the Saved Spectras 
        spectra_Names           %Saves the Autogenerated names for the samples taken
        num_Saved = 0;          %tracks number of saved spectras. 
        saved_Waves
        index = 0;              %holds the index of the spectrometer being used. 
        
                        %Beginning Strings
        xMin_Start               %the default X Min read at the beggining                        
        xMax_Start               %the default X MAx read at the beginning
        
                        %Labels for UIControls
        xMin_Text = 'X axis Min Value';          %label for XMin
        xMax_Text = 'X axis Max Value';          %label for XMax
        scans_Text = 'Number of Scans per Average';   %label for scans
        int_Text = 'Integration Time (ms)';      %label for int time
        light_Back = 'Images/light_background.png';    %address of light sampling backdrop image
        dark_Back = 'Images/dark_background.png';      %address of dark sampling backdrop image
        x_Text = 'Wavelength (nm)';               %label for the x axis
        y_Text = 'Intensity';                     %label for the y axis
        custom_Name = 'Sample Name';              %the default sample name
        filename = 'mySpectras.txt';              %the default file name
        
        
    end
    
    methods
        
        function app = spectra_Class
            %This is the constructor.  It runs when a new object is created
            %it is written in a way to make the graphics between all of
            %the programs fundamentally similar.
            
            [~, xValues] = spectraWizard(app.scans_Num, app.int_Num);
            app.xMin_Num = xValues(1);
            app.xMax_Num = xValues(length(xValues));
            app.xMax_Start = num2str(app.xMax_Num); 
            app.xMin_Start = num2str(app.xMin_Num);
            
            app.body = figure('Position', [0, 20, 1600, 800]);
            app.background = axes('Parent', app.body, 'Position', [0,0,1,1]);
            app.picture = imread('Images/app_background.jpg');
            image(app.background, app.picture)
            axis off
            app.limits_Panel = uipanel( app.body, 'Title', 'Control X Axis', 'Position', [.85,.63 ,.1,.155]);
            app.specta_Panel = uipanel(app.body, 'Title', 'Spectrum Sampling', 'Position', [.85, .8, .1, .17]);
            app.sample_Panel = uipanel(app.body, 'Title', 'Background Sampling', 'Position', [.85, .52, .1, .09]);
            app.xMin = uicontrol(app.limits_Panel, 'Style', 'edit', 'Position', [15, 10, 100, 20], 'String', app.xMin_Start, 'Callback', @app.xMin_Callback); 
            app.xMax = uicontrol(app.limits_Panel, 'Style', 'edit', 'Position', [15, 60, 100, 20], 'String', app.xMax_Start, 'Callback', @app.xMax_Callback);
            app.scans = uicontrol(app.specta_Panel, 'Style', 'edit', 'Position', [15, 10, 100, 20], 'String', num2str(app.scans_Num), 'Callback', @app.scans_Callback); 
            app.integration = uicontrol(app.specta_Panel, 'Style', 'edit', 'Position', [15, 67, 100, 20], 'String', num2str(app.int_Num), 'Callback', @app.int_Callback);
            app.xMin_Label = uicontrol(app.limits_Panel, 'Style', 'text', 'String', app.xMin_Text, 'Position', [15, 35, 100, 20]);          
            app.xMax_Label = uicontrol(app.limits_Panel, 'Style', 'text', 'String', app.xMax_Text, 'Position', [15, 85, 100, 20]); 
            app.scans_Label = uicontrol(app.specta_Panel, 'Style', 'text', 'String', app.scans_Text, 'Position', [15, 33, 100, 30]); 
            app.int_Label = uicontrol(app.specta_Panel, 'Style', 'text', 'String', app.int_Text, 'Position', [15, 88, 100, 20]); 
            app.dark_Sample = uicontrol(app.sample_Panel, 'Style', 'togglebutton', 'String', 'Dark Sample', 'Position', [15, 20, 100, 17], 'Callback', @app.dark_Spectra_Callback);
            app.pause = uicontrol(app.body, 'Style', 'togglebutton', 'String', 'Pause', 'Position', [15, 20, 100, 17], 'Callback', @app.pause_Callback);
            app.close = uicontrol(app.body, 'Style', 'pushbutton', 'String', 'Close', 'Position', [145, 20, 100, 17], 'Callback', @app.close_Callback);
            app.graph = axes('Parent', app.body, 'Position', [.07,.1,.75,.8], 'XLim', [app.xMin_Num, app.xMax_Num]);
            app.custom_Text = uicontrol(app.body, 'Style', 'edit', 'Position', [1070, 70, 200, 20], 'String', app.custom_Name, 'Callback', @app.name_Callback);
            app.delete = uicontrol(app.body, 'Style', 'popupmenu', 'Position', [1000, 100, 50, 20], 'String', app.spectra_Names);
            spectStrings = {'Green Spectrometer (75)'; 'Red Spectrometer (65)'};
            app.spectIndex = uicontrol(app.body, 'Style', 'listbox', 'Position', [1100, 100, 150, 30], 'String', spectStrings, 'Callback', @app.index_Callback);
            
            uistack(app.graph, 'down')
            
        end
    
        %triggered when the text in XMin is changed.  This updates the Xmin
        %of the object, meaning that the axis limits on the next plot will
        %change as well. 
        function xMin_Callback(app, hObject, eventdata)
            
            app.xMin_Num = str2double(get(hObject, 'String'));
            
        end
        
        %triggered when the text in XMax is changed.  This updates the Xmax
        %of the object, meaning that the axis limits on the next plot will
        %change as well. 
        function xMax_Callback(app, hObject, eventdata)
            
            app.xMax_Num = str2double(get(hObject, 'String'));
            
        end
        
        %triggered when the text in the Scans per average field is changed.
        %This updates the scans property of the object, meaning that the
        %number of scans of the next spectrum will change as well.         
        function scans_Callback(app, hObject, eventdata)
            
            app.scans_Num = str2double(get(hObject, 'String'));
            
        end
        
        %triggered when the text in the Integration time field is changed.
        %This updates the int property of the object, meaning that the
        %integration time of the next spectrum will change as well.
        function int_Callback(app, hObject, eventdata)
            
            app.int_Num = str2double(get(hObject, 'String'))*1000;
            
        end
        
        function name_Callback(app, hObject, eventdata)
           
            app.custom_Name = get(hObject, 'String');
            
        end
        
        function index_Callback(app, hObject, eventdata)
            
           ints = get(hObject, 'Value');
           app.index = ints -1;
            
        end
        
        %This function stop the program from graphing temporarily, freezing
        %the latest spectra on the screen. 
        function pause_Callback(app, hObject, eventdata)
            
            pressed = get(hObject, 'Value');
            if pressed == get(hObject, 'Max')
                app.halt = 1;
            elseif pressed == get(hObject, 'Min')
                app.halt = 0;
            end
            
        end
        
        %This function effectivly stops the program from running, and
        %closes the figure. 
        function close_Callback(app, hObject, eventdata)
            
            app.keepGraphing = 0;
            close(app.body)
            
        end
        


        
        %This is a generic plot function which does a few basic actions of
        %plotting.  Many of the subclasses overwride this to some degree,
        %but it takes care of the graphics, as well as updating the
        %darkSpectrum, and preparing data.
        function plotSpectra(app)
            
            uistack(app.graph, 'top')
            
            [app.spectrum, app.wavelengths] = spectraWizard(app.scans_Num, app.int_Num, app.index);
            app.spectrum = app.spectrum - app.dark_Spectrum;
            
            %           app.Spectrum = smoothing(app.Spectrum);
            
            
        end
        
        
        %function monitors the Dark Spectra button, when it is initiated it
        %begins a new dark spectra sampling process.  When it is toggeled
        %off it switches off the sampling process for plot as well. 
        function dark_Spectra_Callback(app, hObject, eventdata)
            
            dark = Backdrop_Sample(app.scans_Num, app.int_Num, app.xMin_Num, app.xMax_Num, app.dark_Back);
            app.dark_Spectrum = dark.back_Spectrum;
            
        end
    end
end

